### ISSUE TITLE
Set onLoadMore in Java

### ISSUE THREAD

**Issue by azizarc88** [swabbass/WardRecycler#1]
How we can set onLoadMore callback in Java ?

**Comment by swabbass** [comment]
Hey, sorry for the late response.
 1.  android studio just can complete it for you if u work with it.
 2. ` wardRecycler.setOnLoadMore(new Function2<Integer, Integer, Unit>() {
           @Override
           public Unit invoke(Integer integer, Integer integer2) {
               return null;
           }
       });`
 3. `wardRecycler.setOnLoadMore((integer, integer2) -> null);`
 4. 01101011 01101111 01110100 01101100 01101001 01101110
